### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by gabriel-vanca** [matthizou/github-show-avatars#6]
It doesn't work

![image](https://github.com/user-attachments/assets/b03f3c1a-a8b7-4008-9bcd-0288f68714c5)

**Comment by matthizou** [comment]
It should work now - try with latest version v1.0.6, on https://github.com/facebook/react/pulls

**Comment by gabriel-vanca** [comment]
Still broken the first time a page loads, but works after force refreshing the page.

![image](https://github.com/user-attachments/assets/a88ae095-6d4d-41bd-be0e-7f48e384f66c)

**Comment by matthizou** [comment]
Thanks for the feedback! My bet would be something specific to your environment (ie: other extensions changing the dom this extension expects) . Any idea?

Tests on my machine (chrome 131): ✅ 
Daily end-to-end tests (where the extension is installed on a chromium browser using puppeter and run on a GHA context): ✅ 

- Can you confirm you are using v1.06?
-  please confirm you don't overwrite specific avatars in the "options" menu of the extension

_broken the first time a page loads, but works after force refreshing the page_ : I wonder why. The extension is stateless, except when overwriting avatars

**Comment by gabriel-vanca** [comment]
Yes, it's v1.06 and I'm not overwriting anything in the config. I've even uninstalled and reinstalled the extension.
I've tested it on Edge 131.0.2903.86 (Official build) (64-bit)

**Comment by gabriel-vanca** [comment]
I've done some further testing and it seems to be fairly random. It doesn't work at first load, then it works upon force reload, then doesn't work at the next force reload, then works again etc etc.

**Comment by matthizou** [comment]
Microsoft Edge?! Right, Chrome extensions can be installed on this browser. I just installed it on my machine (mac), and it seems all is working, even after various page refreshes. 

A few follow-up questions: 
- Can you try in Chrome, see if you have the same issue?
- From the screenshot you sent, the extension seems to work - the extra column is added, the image tag is added. Could it be that the image isn't rendered for some reasons? (in this case, I expect an error message in the console). Or that the html is malformed?
-  (follow-up from last question) Do you have an error message in the console, when it doesn't work?

**Comment by gabriel-vanca** [comment]
This is what I get in the console when trying to load a page.

![image](https://github.com/user-attachments/assets/0089d4db-b163-42e5-a163-14c54bce256d)

![image](https://github.com/user-attachments/assets/c90b4168-86cd-44bf-b042-8421ea8cb02e)

It seems to work in Chrome (though that might be simply because I don't use the same extensions in Chrome).

I'll try next with extensions disabled (will reply a bit later with that).

**Comment by gabriel-vanca** [comment]
Ok, figured it out. It's cause by the _small-user-avatars_ feature in Refined Github (https://github.com/refined-github/refined-github)

https://github.com/refined-github/refined-github/blob/main/source/features/small-user-avatars.tsx

<img width="708" alt="271184107-24ec471e-54d1-434a-a5f2-615902d2cad9" src="https://github.com/user-attachments/assets/d8f99fd8-8b6d-449b-aa5b-7818d1fb7012" />
